config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pe_exchanges
  resources :pe_trade_exchanges
  resources :pe_exchange_products
  resources :pe_recommends
  resources :pe_exchange_commons
  resources :pe_products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pe_exchange.rb
class PeExchange < ApplicationRecord
end

app/controllers/pe_exchanges_controller.rb
class PeExchangesController < ApplicationController
  before_action :set_pe_exchange, only: [:show, :edit, :update, :destroy]

  # GET /pe_exchanges
  # GET /pe_exchanges.json
  def index
    @pe_exchanges = PeExchange.all

    respond_to do |format|
      format.json { render :json => @pe_exchanges }
    end
  end

  # GET /pe_exchanges/1
  # GET /pe_exchanges/1.json
  def show
  end

  # GET /pe_exchanges/new
  def new
    @pe_exchange = PeExchange.new
  end

  # GET /pe_exchanges/1/edit
  def edit
  end

  # POST /pe_exchanges
  # POST /pe_exchanges.json
  def create
    @pe_exchange = PeExchange.new(pe_exchange_params)

    respond_to do |format|
      if @pe_exchange.save
        format.html { redirect_to @pe_exchange, notice: 'Pe exchange was successfully created.' }
        format.json { render :show, status: :created, location: @pe_exchange }
      else
        format.html { render :new }
        format.json { render json: @pe_exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pe_exchanges/1
  # PATCH/PUT /pe_exchanges/1.json
  def update
    respond_to do |format|
      if @pe_exchange.update(pe_exchange_params)
        format.html { redirect_to @pe_exchange, notice: 'Pe exchange was successfully updated.' }
        format.json { render :show, status: :ok, location: @pe_exchange }
      else
        format.html { render :edit }
        format.json { render json: @pe_exchange.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pe_exchanges/1
  # DELETE /pe_exchanges/1.json
  def destroy
    @pe_exchange.destroy
    respond_to do |format|
      format.html { redirect_to pe_exchanges_url, notice: 'Pe exchange was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pe_exchange
      @pe_exchange = PeExchange.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pe_exchange_params
      params.require(:pe_exchange).permit(:user_id, :prize_date, :product_d, :name, :phone, :address1, :address2, :city, :state, :zip, :id_card, :status)
    end
end

app/helpers/pe_exchanges_helper.rb
module PeExchangesHelper
end

app/views/pe_exchanges/_form.html.erb
<%= form_with(model: pe_exchange, local: true) do |form| %>
  <% if pe_exchange.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pe_exchange.errors.count, "error") %> prohibited this pe_exchange from being saved:</h2>

      <ul>
        <% pe_exchange.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :prize_date %>
    <%= form.date_select :prize_date %>
  </div>

  <div class="field">
    <%= form.label :product_d %>
    <%= form.text_field :product_d %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div class="field">
    <%= form.label :address1 %>
    <%= form.text_field :address1 %>
  </div>

  <div class="field">
    <%= form.label :address2 %>
    <%= form.text_field :address2 %>
  </div>

  <div class="field">
    <%= form.label :city %>
    <%= form.text_field :city %>
  </div>

  <div class="field">
    <%= form.label :state %>
    <%= form.text_field :state %>
  </div>

  <div class="field">
    <%= form.label :zip %>
    <%= form.text_field :zip %>
  </div>

  <div class="field">
    <%= form.label :id_card %>
    <%= form.text_field :id_card %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.check_box :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pe_exchanges/edit.html.erb
<h1>Editing Pe Exchange</h1>

<%= render 'form', pe_exchange: @pe_exchange %>

<%= link_to 'Show', @pe_exchange %> |
<%= link_to 'Back', pe_exchanges_path %>

app/views/pe_exchanges/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pe Exchanges</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Prize date</th>
      <th>Product d</th>
      <th>Name</th>
      <th>Phone</th>
      <th>Address1</th>
      <th>Address2</th>
      <th>City</th>
      <th>State</th>
      <th>Zip</th>
      <th>Id card</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pe_exchanges.each do |pe_exchange| %>
      <tr>
        <td><%= pe_exchange.user_id %></td>
        <td><%= pe_exchange.prize_date %></td>
        <td><%= pe_exchange.product_d %></td>
        <td><%= pe_exchange.name %></td>
        <td><%= pe_exchange.phone %></td>
        <td><%= pe_exchange.address1 %></td>
        <td><%= pe_exchange.address2 %></td>
        <td><%= pe_exchange.city %></td>
        <td><%= pe_exchange.state %></td>
        <td><%= pe_exchange.zip %></td>
        <td><%= pe_exchange.id_card %></td>
        <td><%= pe_exchange.status %></td>
        <td><%= link_to 'Show', pe_exchange %></td>
        <td><%= link_to 'Edit', edit_pe_exchange_path(pe_exchange) %></td>
        <td><%= link_to 'Destroy', pe_exchange, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pe Exchange', new_pe_exchange_path %>

app/views/pe_exchanges/new.html.erb
<h1>New Pe Exchange</h1>

<%= render 'form', pe_exchange: @pe_exchange %>

<%= link_to 'Back', pe_exchanges_path %>

app/views/pe_exchanges/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @pe_exchange.user_id %>
</p>

<p>
  <strong>Prize date:</strong>
  <%= @pe_exchange.prize_date %>
</p>

<p>
  <strong>Product d:</strong>
  <%= @pe_exchange.product_d %>
</p>

<p>
  <strong>Name:</strong>
  <%= @pe_exchange.name %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @pe_exchange.phone %>
</p>

<p>
  <strong>Address1:</strong>
  <%= @pe_exchange.address1 %>
</p>

<p>
  <strong>Address2:</strong>
  <%= @pe_exchange.address2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @pe_exchange.city %>
</p>

<p>
  <strong>State:</strong>
  <%= @pe_exchange.state %>
</p>

<p>
  <strong>Zip:</strong>
  <%= @pe_exchange.zip %>
</p>

<p>
  <strong>Id card:</strong>
  <%= @pe_exchange.id_card %>
</p>

<p>
  <strong>Status:</strong>
  <%= @pe_exchange.status %>
</p>

<%= link_to 'Edit', edit_pe_exchange_path(@pe_exchange) %> |
<%= link_to 'Back', pe_exchanges_path %>