config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pe_exchanges
  resources :pe_trade_exchanges
  resources :pe_exchange_products
  resources :pe_recommends
  resources :pe_exchange_commons
  resources :pe_products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pe_exchange_product.rb
class PeExchangeProduct < ApplicationRecord

  belongs_to :pe_product

  def readable_object(hash = nil)
    ret = {}

    ret = {
        :id => self.id,
        :groupId => self.group_id,
        :order => self.order,
        :productId => self.pe_product_id,
        :productType => self.price_type,
        :price => self.price,
        :limit => self.limit,
        :status => self.status,
    }

    if hash && hash[:include]

      if hash[:include].include?(:pe_product)
        ret[:peProduct] = self.pe_product.readable_object
      end

    end
    ret
  end

end

app/controllers/pe_exchange_products_controller.rb
class PeExchangeProductsController < ApplicationController
  before_action :set_pe_exchange_product, only: [:show, :edit, :update, :destroy]

  # GET /pe_exchange_products
  # GET /pe_exchange_products.json
  def index
    @pe_exchange_products = PeExchangeProduct.all.page(params[:page]).per(params[:per_page])
    respond_to do |format|
      format.html
      format.json { render json:
                               list_json(@pe_exchange_products, :include => [:pe_product])
      }
    end
  end

  # GET /pe_exchange_products/1
  # GET /pe_exchange_products/1.json
  def show
  end

  # GET /pe_exchange_products/new
  def new
    @pe_exchange_product = PeExchangeProduct.new
  end

  # GET /pe_exchange_products/1/edit
  def edit
  end

  # POST /pe_exchange_products
  # POST /pe_exchange_products.json
  def create
    @pe_exchange_product = PeExchangeProduct.new(pe_exchange_product_params)

    respond_to do |format|
      if @pe_exchange_product.save
        format.html { redirect_to @pe_exchange_product, notice: 'Pe exchange product was successfully created.' }
        format.json { render :show, status: :created, location: @pe_exchange_product }
      else
        format.html { render :new }
        format.json { render json: @pe_exchange_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pe_exchange_products/1
  # PATCH/PUT /pe_exchange_products/1.json
  def update
    respond_to do |format|
      if @pe_exchange_product.update(pe_exchange_product_params)
        format.html { redirect_to @pe_exchange_product, notice: 'Pe exchange product was successfully updated.' }
        format.json { render :show, status: :ok, location: @pe_exchange_product }
      else
        format.html { render :edit }
        format.json { render json: @pe_exchange_product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pe_exchange_products/1
  # DELETE /pe_exchange_products/1.json
  def destroy
    @pe_exchange_product.destroy
    respond_to do |format|
      format.html { redirect_to pe_exchange_products_url, notice: 'Pe exchange product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pe_exchange_product
      @pe_exchange_product = PeExchangeProduct.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pe_exchange_product_params
      params.require(:pe_exchange_product).permit(:group_id, :order, :pe_product_id, :price_type, :price, :limit, :status)
    end
end

app/helpers/pe_exchange_products_helper.rb
module PeExchangeProductsHelper
end

app/views/pe_exchange_products/_form.html.erb
<%= form_with(model: pe_exchange_product, local: true) do |form| %>
  <% if pe_exchange_product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pe_exchange_product.errors.count, "error") %> prohibited this pe_exchange_product from being saved:</h2>

      <ul>
        <% pe_exchange_product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :group_id %>
    <%= form.text_field :group_id %>
  </div>

  <div class="field">
    <%= form.label :order %>
    <%= form.text_field :order %>
  </div>

  <div class="field">
    <%= form.label :pe_product_id %>
    <%= form.text_field :pe_product_id %>
  </div>

  <div class="field">
    <%= form.label :price_type %>
    <%= form.text_field :price_type %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :limit %>
    <%= form.text_field :limit %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pe_exchange_products/edit.html.erb
<h1>Editing Pe Exchange Product</h1>

<%= render 'form', pe_exchange_product: @pe_exchange_product %>

<%= link_to 'Show', @pe_exchange_product %> |
<%= link_to 'Back', pe_exchange_products_path %>

app/views/pe_exchange_products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pe Exchange Products</h1>

<table>
  <thead>
    <tr>
      <th>Group</th>
      <th>Order</th>
      <th>Product</th>
      <th>Price type</th>
      <th>Price</th>
      <th>Limit</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pe_exchange_products.each do |pe_exchange_product| %>
      <tr>
        <td><%= pe_exchange_product.group_id %></td>
        <td><%= pe_exchange_product.order %></td>
        <td><%= pe_exchange_product.pe_product_id %></td>
        <td><%= pe_exchange_product.price_type %></td>
        <td><%= pe_exchange_product.price %></td>
        <td><%= pe_exchange_product.limit %></td>
        <td><%= pe_exchange_product.status %></td>
        <td><%= link_to 'Show', pe_exchange_product %></td>
        <td><%= link_to 'Edit', edit_pe_exchange_product_path(pe_exchange_product) %></td>
        <td><%= link_to 'Destroy', pe_exchange_product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pe Exchange Product', new_pe_exchange_product_path %>

app/views/pe_exchange_products/new.html.erb
<h1>New Pe Exchange Product</h1>

<%= render 'form', pe_exchange_product: @pe_exchange_product %>

<%= link_to 'Back', pe_exchange_products_path %>

app/views/pe_exchange_products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Group:</strong>
  <%= @pe_exchange_product.group_id %>
</p>

<p>
  <strong>Order:</strong>
  <%= @pe_exchange_product.order %>
</p>

<p>
  <strong>Product:</strong>
  <%= @pe_exchange_product.pe_product_id %>
</p>

<p>
  <strong>Price type:</strong>
  <%= @pe_exchange_product.price_type %>
</p>

<p>
  <strong>Price:</strong>
  <%= @pe_exchange_product.price %>
</p>

<p>
  <strong>Limit:</strong>
  <%= @pe_exchange_product.limit %>
</p>

<p>
  <strong>Status:</strong>
  <%= @pe_exchange_product.status %>
</p>

<%= link_to 'Edit', edit_pe_exchange_product_path(@pe_exchange_product) %> |
<%= link_to 'Back', pe_exchange_products_path %>