config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pe_exchanges
  resources :pe_trade_exchanges
  resources :pe_exchange_products
  resources :pe_recommends
  resources :pe_exchange_commons
  resources :pe_products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pe_recommend.rb
class PeRecommend < ApplicationRecord

  belongs_to :pe_product

  def readable_object(hash = nil)
    ret = {}

    ret = {
        :id => self.id,
        :order => self.order,
        :productId => self.pe_product_id
    }

    if hash && hash[:include]

      if hash[:include].include?(:pe_product)
        ret[:peProduct] = self.pe_product.readable_object
      end

    end
    ret
  end
end

app/controllers/pe_recommends_controller.rb
class PeRecommendsController < ApplicationController
  before_action :set_pe_recommend, only: [:show, :edit, :update, :destroy]

  # GET /pe_recommends
  # GET /pe_recommends.json
  def index
    @pe_recommends = PeRecommend.all.page(params[:page]).per(params[:per_page]).order("'order' asc")
    respond_to do |format|
      format.html
      format.json { render json:
                               list_json(@pe_recommends, :include => [:pe_product])
      }
    end
  end

  # GET /pe_recommends/1
  # GET /pe_recommends/1.json
  def show
  end

  # GET /pe_recommends/new
  def new
    @pe_recommend = PeRecommend.new
  end

  # GET /pe_recommends/1/edit
  def edit
  end

  # POST /pe_recommends
  # POST /pe_recommends.json
  def create
    @pe_recommend = PeRecommend.new(pe_recommend_params)

    respond_to do |format|
      if @pe_recommend.save
        format.html { redirect_to @pe_recommend, notice: 'Pe recommend was successfully created.' }
        format.json { render :show, status: :created, location: @pe_recommend }
      else
        format.html { render :new }
        format.json { render json: @pe_recommend.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pe_recommends/1
  # PATCH/PUT /pe_recommends/1.json
  def update
    respond_to do |format|
      if @pe_recommend.update(pe_recommend_params)
        format.html { redirect_to @pe_recommend, notice: 'Pe recommend was successfully updated.' }
        format.json { render :show, status: :ok, location: @pe_recommend }
      else
        format.html { render :edit }
        format.json { render json: @pe_recommend.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pe_recommends/1
  # DELETE /pe_recommends/1.json
  def destroy
    @pe_recommend.destroy
    respond_to do |format|
      format.html { redirect_to pe_recommends_url, notice: 'Pe recommend was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pe_recommend
    @pe_recommend = PeRecommend.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pe_recommend_params
    params.require(:pe_recommend).permit(:order, :pe_product_id)
  end
end

app/helpers/pe_recommends_helper.rb
module PeRecommendsHelper
end

app/views/pe_recommends/_form.html.erb
<%= form_with(model: pe_recommend, local: true) do |form| %>
  <% if pe_recommend.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pe_recommend.errors.count, "error") %> prohibited this pe_recommend from being saved:</h2>

      <ul>
        <% pe_recommend.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order %>
    <%= form.text_field :order %>
  </div>

  <div class="field">
    <%= form.label :pe_product_id %>
    <%= form.text_field :pe_product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pe_recommends/edit.html.erb
<h1>Editing Pe Recommend</h1>

<%= render 'form', pe_recommend: @pe_recommend %>

<%= link_to 'Show', @pe_recommend %> |
<%= link_to 'Back', pe_recommends_path %>

app/views/pe_recommends/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pe Recommends</h1>

<table>
  <thead>
    <tr>
      <th>Order</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pe_recommends.each do |pe_recommend| %>
      <tr>
        <td><%= pe_recommend.order %></td>
        <td><%= pe_recommend.pe_product_id %></td>
        <td><%= link_to 'Show', pe_recommend %></td>
        <td><%= link_to 'Edit', edit_pe_recommend_path(pe_recommend) %></td>
        <td><%= link_to 'Destroy', pe_recommend, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pe Recommend', new_pe_recommend_path %>

app/views/pe_recommends/new.html.erb
<h1>New Pe Recommend</h1>

<%= render 'form', pe_recommend: @pe_recommend %>

<%= link_to 'Back', pe_recommends_path %>

app/views/pe_recommends/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Order:</strong>
  <%= @pe_recommend.order %>
</p>

<p>
  <strong>Product:</strong>
  <%= @pe_recommend.pe_product_id %>
</p>

<%= link_to 'Edit', edit_pe_recommend_path(@pe_recommend) %> |
<%= link_to 'Back', pe_recommends_path %>