config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  resources :pe_exchanges
  resources :pe_trade_exchanges
  resources :pe_exchange_products
  resources :pe_recommends
  resources :pe_exchange_commons
  resources :pe_products
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/pe_exchange_common.rb
class PeExchangeCommon < ApplicationRecord
  has_one_attached :banner

  def readable_object(hash = nil)
    ret = {}
    # case version.to_i
    # when 1
    # end
    ret = {
        :banner => self.banner.attached? ? Rails.application.routes.url_helpers.url_for(self.banner) : "",
        :interval => self.interval,
        :maintenance => self.maintenance
    }
    ret

  end

end

app/controllers/pe_exchange_commons_controller.rb
class PeExchangeCommonsController < ApplicationController
  before_action :set_pe_exchange_common, only: [:show, :edit, :update, :destroy]
  # before_action :set_host_for_local_storage
  # #
  # private
  # def set_host_for_local_storage
  #   ActiveStorage::Current.host = request.base_url if Rails.application.config.active_storage.service == :local
  # end

  # GET /pe_exchange_commons
  # GET /pe_exchange_commons.json
  def index
    @pe_exchange_commons = PeExchangeCommon.all.page(params[:page]).per(params[:per_page])
    respond_to do |format|
      format.html
      format.json { render json:
                               list_json(@pe_exchange_commons)
      }
    end
  end


  # GET /pe_exchange_commons/1
  # GET /pe_exchange_commons/1.json
  def show
  end

  # GET /pe_exchange_commons/new
  def new
    @pe_exchange_common = PeExchangeCommon.new
  end

  # GET /pe_exchange_commons/1/edit
  def edit
  end

  # POST /pe_exchange_commons
  # POST /pe_exchange_commons.json
  def create
    @pe_exchange_common = PeExchangeCommon.new(pe_exchange_common_params)

    respond_to do |format|
      if @pe_exchange_common.save
        format.html { redirect_to @pe_exchange_common, notice: 'Pe exchange common was successfully created.' }
        format.json { render :show, status: :created, location: @pe_exchange_common }
      else
        format.html { render :new }
        format.json { render json: @pe_exchange_common.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pe_exchange_commons/1
  # PATCH/PUT /pe_exchange_commons/1.json
  def update
    respond_to do |format|
      if @pe_exchange_common.update(pe_exchange_common_params)
        format.html { redirect_to @pe_exchange_common, notice: 'Pe exchange common was successfully updated.' }
        format.json { render :show, status: :ok, location: @pe_exchange_common }
      else
        format.html { render :edit }
        format.json { render json: @pe_exchange_common.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pe_exchange_commons/1
  # DELETE /pe_exchange_commons/1.json
  def destroy
    @pe_exchange_common.destroy
    respond_to do |format|
      format.html { redirect_to pe_exchange_commons_url, notice: 'Pe exchange common was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_pe_exchange_common
    @pe_exchange_common = PeExchangeCommon.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def pe_exchange_common_params
    params.require(:pe_exchange_common).permit(:banner, :interval, :maintenance)
  end
end

app/helpers/pe_exchange_commons_helper.rb
module PeExchangeCommonsHelper
end

app/views/pe_exchange_commons/_form.html.erb
<%= form_with(model: pe_exchange_common, local: true) do |form| %>
  <% if pe_exchange_common.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(pe_exchange_common.errors.count, "error") %> prohibited this pe_exchange_common from being saved:</h2>

      <ul>
        <% pe_exchange_common.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :banner %>
    <%= form.text_field :banner %>
  </div>

  <div class="field">
    <%= form.label :interval %>
    <%= form.text_field :interval %>
  </div>

  <div class="field">
    <%= form.label :maintenance %>
    <%= form.check_box :maintenance %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pe_exchange_commons/edit.html.erb
<h1>Editing Pe Exchange Common</h1>

<%= render 'form', pe_exchange_common: @pe_exchange_common %>

<%= link_to 'Show', @pe_exchange_common %> |
<%= link_to 'Back', pe_exchange_commons_path %>

app/views/pe_exchange_commons/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pe Exchange Commons</h1>

<table>
  <thead>
    <tr>
      <th>Banner</th>
      <th>Interval</th>
      <th>Maintenance</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pe_exchange_commons.each do |pe_exchange_common| %>
      <tr>
        <td><%= pe_exchange_common.banner %></td>
        <td><%= pe_exchange_common.interval %></td>
        <td><%= pe_exchange_common.maintenance %></td>
        <td><%= link_to 'Show', pe_exchange_common %></td>
        <td><%= link_to 'Edit', edit_pe_exchange_common_path(pe_exchange_common) %></td>
        <td><%= link_to 'Destroy', pe_exchange_common, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Pe Exchange Common', new_pe_exchange_common_path %>

app/views/pe_exchange_commons/new.html.erb
<h1>New Pe Exchange Common</h1>

<%= render 'form', pe_exchange_common: @pe_exchange_common %>

<%= link_to 'Back', pe_exchange_commons_path %>

app/views/pe_exchange_commons/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Banner:</strong>
  <%= @pe_exchange_common.banner %>
</p>

<p>
  <strong>Interval:</strong>
  <%= @pe_exchange_common.interval %>
</p>

<p>
  <strong>Maintenance:</strong>
  <%= @pe_exchange_common.maintenance %>
</p>

<%= link_to 'Edit', edit_pe_exchange_common_path(@pe_exchange_common) %> |
<%= link_to 'Back', pe_exchange_commons_path %>